// Real Google reviews from the firm, extracted from the migrated reviews page.
// Verbatim client text; do not edit wording.

export type Review = { author: string; when: string; stars: number; text: string };

export const REVIEWS: Review[] = [
  { author: "James Ealy", when: "1 month ago", stars: 5, text: "I couldn\u2019t be happier with the outcome Quality, law firm, and a quality price" },
  { author: "David Stephan", when: "1 month ago", stars: 5, text: "I cannot recommend Farris Law Firm enough! They handled my case from start to finish with complete professionalism and expertise. They delivered on every promise they made during our initial consultation. What impressed me most was that I didn't even need to appear in court - they took care of everything on my behalf. The entire process was smooth, stress-free, and the outcome was exactly what we hoped for. If you're looking for a law firm that actually does what they say they'll do, look no further than Farris Law Firm. Their knowledge, communication, and dedication to their clients is outstanding. Thank you for giving me a fresh start!" },
  { author: "Derek Daza", when: "2 months ago", stars: 5, text: "Great communication, extremely helpful, willing to workout payment methods with you and able to get the results that are discussed. Best law firm I've interacted with each step of the way." },
  { author: "Jennifer-Athena Wakalopulos", when: "2 months ago", stars: 5, text: "Working with Mr. Charles Farris gave me a new found hope that there are still lawyers who genuinely care about you as a person and don\u2019t just think of every penny they can squeeze out of you!! I chose Mr. Farris because he made me feel seen and heard and that matters when you want to move forward. Thank you for your gracious support & guidance. I highly recommend Farris Law Firm!" },
  { author: "Leah Gadallah", when: "2 months ago", stars: 5, text: "Charles and his firm helped me swiftly and efficiently dismiss a case that should have never existed in the first place. Their professionalism and prompt action made all the difference. I would confidently recommend Charles and his team to anyone in need of excellent legal support." },
  { author: "Peter DiVito", when: "4 months ago", stars: 5, text: "Charles and his team are absolutely lovely to work with! They are responsive, thoughtful and great at what they do. They were able to get a speeding ticket dismissed. I am so very grateful for their hard work. I can not recommend them enough." },
  { author: "Fae Podskarbi", when: "5 months ago", stars: 5, text: "I cannot say enough about Attorney Charles Ferris. My husband and I hired him through the law firm during Covid in 2020, and even without meeting in person, his results spoke louder than words. He is knowledgeable, dedicated, and goes above and beyond for his clients. We truly owe him more than we can ever thank him for\u2014his work changed our lives. Five years later, if I ever need legal help again, he will be the first person I call. Unlike many lawyers who only make promises, Charles Ferris delivers real results. Highly recommended! I\u2019m so glad I found him on Yelp and could write this review because he is well deserved." },
  { author: "DeLisa Foreman", when: "6 months ago", stars: 5, text: "I truly can\u2019t speak highly enough about Farris Law Firm. My family was dealing with three serious traffic tickets that could have resulted in license points, increased insurance premiums, and a whole lot of stress. But thanks to Charles, every single charge was dismissed. From the very beginning, Charles and Stephanie at Farris Law Firm were professional, attentive, and clearly experts in their field. They guided us through the entire process with transparency and care, keeping us informed at every step. What could have been a major headache was handled smoothly and efficiently. What stood out most was their confidence, clarity, and genuine commitment to achieving the best outcome. It was immediately clear that we were in capable hands. If you need a reliable, knowledgeable legal team that actually gets results, look no further than Farris. I wouldn\u2019t trust anyone else. Thank you again for everything\u2014you saved us time, money, and gave us real peace of mind!" },
  { author: "Michael Moore Jr", when: "7 months ago", stars: 5, text: "I had a great experience working with Farris Law Firm. They handled my petition to seal and destroy records with professionalism, efficiency, and a deep understanding of the law. My attorney was thorough in explaining the process, responsive to all of my questions, and truly fought for the best possible outcome. Thanks to their hard work, my petition was granted without unnecessary delays. I felt confident and supported every step of the way. If you\u2019re looking for a law firm that gets results and genuinely cares about helping you move forward in life, I highly recommend Farris Law Firm. Thanks a ton!" },
  { author: "Tess leviste", when: "7 months ago", stars: 5, text: "The expungement process was handled incredibly well. We didn't have to do anything but wait, they took care of everything seamlessly. The service was efficient, professional, and exceeded our expectations. We're very thankful and truly happy with the outcome!" },
  { author: "Mark Quinlan", when: "7 months ago", stars: 5, text: "Charles is helping me right now, but, I gotta say, he's such a calm in the storm. Guy knows his stuff and he's incredibly punctual. He's helping me make the best case possible. I have anxiety, and he knows how to talk to me in a way that centers me but keeps things moving. You've been a world of help; thank you for all you've done." },
  { author: "Jesse Boone", when: "7 months ago", stars: 5, text: "It's difficult to navigate a tense situation, and I had no idea how to prepare anything. Charles was recommended to me by a couple of friends, and I'm glad I went with him. He had a sharp way of breaking things down so I could understand what our best options were. He was patient with me and got me the best possible outcome. I remain grateful for all he did; he's definitely getting a holiday card." },
  { author: "Liz Richman", when: "8 months ago", stars: 5, text: "Charles is wonderful! When I needed assistance with a legal matter, he provided invaluable guidance and expertise. His attentiveness, responsiveness, and willingness to thoroughly answer all my questions made the entire process seamless. I feel incredibly confident in my decision to seek his counsel and highly recommend his services." },
  { author: "Raymond Garcia", when: "8 months ago", stars: 5, text: "I highly recommend Charles Farris. He was very helpful and kept to his promises. Always willing to work hard for you. He will always be my lawyer." },
  { author: "mark Buckley", when: "9 months ago", stars: 5, text: "Best Lawyer in the AV. Very professional, honest and has great pricing. He gets the job done." },
  { author: "Rose Anne Brown", when: "10 months ago", stars: 5, text: "Charles was an incredible help to me. He listened to my concerns, gave thorough explanations, was professional, knowledgeable, and caring. He is an expert in his field!" },
  { author: "Charlotte Farris", when: "11 months ago", stars: 5, text: "Attorney Charles Farris demonstrates a dedicated & thorough attention to the law & the legal cases he represents. He is impressive in his work. CEF" },
  { author: "Elaine Sturkey", when: "11 months ago", stars: 5, text: "Attorney Charles Farris provided me with competent representation in my legal matter. While he did not promise a certain outcome, he did fairly promise to get me the best possible outcome and that promise was fulfilled! Attorney Farris inspired confidence as he kept me informed throughout the proceedings of my case and was available to answer all of my questions. I would recommend Attorney Farris and his firm based on my experience and interaction with the law firm." },
  { author: "Meg Glazer", when: "11 months ago", stars: 5, text: "So, on a trip to LA earlier this year I was unfortunate enough to receive a speeding ticket and DUI on the 405 after an evening out. I was frantic but Attorney Charles Farris and his understanding team patiently walked me through the process and were able to negotiate the results that were best for me. Relieved and thankful, this isn\u2019t anything I could have done on my own. Thank you, Charles at Farris Law Firm! You\u2019re the best Meg Glazer" },
  { author: "Ric Delarama", when: "1 year ago", stars: 5, text: "I highly recomend the Farris Law Firm for any criminal case that you might need assistance. Charles Farris was really great, explain everthing to me.on how he is going to defend my case and will fight to dismiss it, in which my case was dismissed. Very nice and friendly person, I highly recomend his Law Firm" },
  { author: "Joshua Baron", when: "1 year ago", stars: 5, text: "Charles takes great care of his clients. He really cares and helps knows how to get results. I love how open he is. Some lawyers try to scare their clients into hiring them. Charles shoots straight and guides his clients to a great outcome. I highly recommend him." },
  { author: "Heidianne Dutch", when: "1 year ago", stars: 5, text: "Charles Ferris was fast and efficient my case was handled with professionalism and ease thank you so much for taking care of me" },
  { author: "Jennifer Peralta", when: "1 year ago", stars: 5, text: "Charles is truly exceptional. I was referred to him by the San Fernando Valley Bar Association, and from the moment we spoke, he put my mind at ease during one of the most stressful times in my life. I was terrified at the thought of being served with a restraining order, but Charles\u2019s calm and confident attitude reassured me. He explained every step of the process, kept in constant communication, and guided me through what felt like an overwhelming situation. Thanks to his expertise and dedication, Charles successfully had the restraining order dropped after three court hearings. Not only was it resolved, but it also never appeared on my background check, which was a huge relief. What truly sets Charles apart is his professionalism and genuine care for his clients. He\u2019s easy to communicate with, intelligent, patient, and pays close attention to every detail. Despite being new to running his own law firm, he brings a wealth of experience to the table and seems deeply committed to achieving the best outcomes whether it\u2019s getting a case dropped or winning it. His dedication and exceptional work make it easy to see why he\u2019s so highly respected. I can\u2019t recommend him enough; he\u2019s truly the best of the best." },
  { author: "Todd & Holly Goldsworthy", when: "1 year ago", stars: 5, text: "Charles was the first call I made after my son was arrested. He put us at ease, helped us through each step of the process, and gave us peace of mind that everything was going to be okay. And it was. Thank you Charles for everything!" },
  { author: "robert stohr", when: "1 year ago", stars: 5, text: "Charles is really easy to work with, he lets you know exactly what to expect and in my case i got the desired outcome without having to do much at all. Really glad I called Charles i\u2019m definitely going to save his number," },
  { author: "Alex L", when: "1 year ago", stars: 5, text: "Im from the Bay Area and l got a d.u.i while on vacation in Los Angeles. I knew I needed someone to represent me for the best outcome possible and I stumbled across Charles. He made the process stress free and did his job thoroughly for the best possible outcome(NO JAIL TIME). Since I live in the Bay Area he made all appearances without me having to go back to L.a \u201cAt all\u201d which was a blessing in itself.After court he kept me in the loop and was very professional how he handled my case. If I called or text him and he wasn\u2019t available he always got back to me in a timely fashion. If you want someone whom really has a passion for what they do I\u2019d choose him. Thanks again Charles to you and your team. It\u2019s highly appreciated for all that you\u2019ve done" },
  { author: "S singer", when: "1 year ago", stars: 5, text: "Charles is the best lawyer you can get. He is extremley thoughtful and proffessional and will explain anything you are confused about so your confident in each step you take with him. I highly reccomend him if you want to win your case and feel confortable the whole proccess! I ended up not having anything on my record and was super lucky:)" },
  { author: "Anya McGanty", when: "1 year ago", stars: 5, text: "Charles was incredibly helpful in walking me through the process to get a medical suspension lifted on my drivers license. He was very thoughtful and always very easy to get a hold of. Would highly recommend if you\u2019re ever in an unfortunate position of needing a traffic lawyer." },
  { author: "GokS", when: "1 year ago", stars: 5, text: "Charles helped me get through my DUI case and to get it dropped to a lesser sentencing. A pro lawyer and a great human. Thank you" },
  { author: "CONSULTOR LABORAL", when: "1 year ago", stars: 5, text: "The Best \u2b50\ufe0f\u2b50\ufe0f\u2b50\ufe0f\u2b50\ufe0f\u2b50\ufe0f" },
  { author: "Jake Rogers", when: "2 years ago", stars: 5, text: "I\u2019ve had multiple attorneys represent me in my life, but Charles handled things a bit differently. Not only is he patient and understanding, but also thorough, and compassionate on a personal level that allows you to trust him fully. He handled my case very professionally and got me an outcome better than I could have expected. I hope to not need his assistance in the future, but would surely return if need be. I highly recommend" },
];

export const REVIEW_COUNT = REVIEWS.length;