// Real client testimonials from the migrated testimonials page. Verbatim text.

export type Testimonial = { author: string; text: string };

export const TESTIMONIALS_FULL: Testimonial[] = [
  { author: "A. Auerbach", text: "My case was a little complicated because I was charged with two DUIs back to back. Charles was in charge for my second one and that one was the one I was most worried about because getting a second one, of course, only worsens the situation. Charles was amazing, he really did a great job representing me and the whole time I was living out of state too. Overall all I had was a fine and a short online class I had to do, and I couldn\u2019t believe it. Charles must have worked magic in the courtroom! Overall having Charles represent me was one of the greatest decisions I\u2019ve made. He and the law firm made the experience so much less stressful and the outcome was great. I definitely recommend hiring Charles Farris as your attorney!" },
  { author: "G. Weins", text: "Amazing work! From start to finish everything was so smooth and easy, Charles Farris made this case so easy and even though my case took many twist and turns that were typically unexpected he managed to easily work through them and get us exactly what we wanted with little to no other repercussions. Can\u2019t really ask for a better outcome. Highly recommended." },
  { author: "J. Rogers", text: "I\u2019ve had multiple attorneys represent me in my life, but Charles handled things a bit differently. Not only is he patient and understanding, but also thorough, and compassionate on a very personal level that allows you to trust him fully. He handled my case very professionally and got me an outcome better than I could have expected. I hope to not need his assistance in the future, but would surely return if need be. I highly recommend." },
  { author: "B.S.", text: "I received a traffic citation in Glendale and Farris Law Firm got it dismissed! I really appreciated their communication with me and their professionalism. As a client, I felt very supported." },
  { author: "anonymous client", text: "My attorney Charles Farris came to bat for me, providing me with his incredible wealth of knowledge, expertise, and most of all kindness. His assistant kept me updated on everything I needed to know, making the entire experience leading up to my court dates much less stressful. When you\u2019re going through a legal process for the first time in your life, it\u2019s important to have people like Mr. Farris on your side. The firm made the entire process so much easier to navigate, because without them, I would have been lost." },
  { author: "anonymous client", text: "We were very pleased with our representation by Charles Farris who went to bat for us in a recent court case. He was professional and thorough as well as responsive. He made the whole process less worrisome and needless to say we had a positive outcome. We would recommend him without reservation." },
];
